name: DUSD Monitor

on:
  schedule:
    - cron: '2-57/5 * * * *'  # 每 5 分钟运行（UTC 时区）
  workflow_dispatch:  # 支持手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 拉取代码
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'  # Node 版本
          cache: 'npm'  # 缓存依赖
      - name: Install dependencies
        run: npm ci  # 安装依赖
      - name: Run monitor script
        env:  # 注入 Secrets 变量
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        run: node app.js  # 运行脚本（cron 自动循环）